let isBulbOn = true; 
console.log(!isBulbOn);
let isBatteryOn = true; 
let isPowerOn = false; 
console.log(!(isBatteryOn && isPowerOn));
let isBatteryOn1 = true; 
let isPowerOn1 = false; 
console.log(isBatteryOn1 && isPowerOn1); 
console.log(!(isBatteryOn1 && isPowerOn1));
let isLoanApproved = true; 
let cash = 30000; 
let cost = 40000; 
const isCarBought = isLoanApproved || (cash > cost); 
console.log(isCarBought);
let cloudStorage = 4; 
let systemStorage = 8; 
let fileSize = 5; 
const result = (cloudStorage > fileSize) || (systemStorage > fileSize); 
console.log("Saved? : " + result);